#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

. ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/load_config

PLAY_PATH="play-$VERSION/"

BUILD_COMMAND="${OPENSHIFT_DATA_DIR}${PLAY_PATH}play clean stage"

cd ${OPENSHIFT_REPO_DIR}

nohup ${BUILD_COMMAND}