#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

cd ${OPENSHIFT_DATA_DIR}

${OPENSHIFT_REPO_DIR}.openshift/action_hooks/stop

export PLAY_LOG_PATH=${OPENSHIFT_DIY_LOG_DIR}

cd ${OPENSHIFT_REPO_DIR}

#TODO specify memory size
#export _JAVA_OPTIONS="-Xms800m -Xmx1500m -XX:PermSize=64m -XX:MaxPermSize=256m"

APP_COMMAND="${OPENSHIFT_REPO_DIR}target/universal/stage/bin/reviyou "\
"-Dhttp.port=${OPENSHIFT_DIY_PORT} "\
"-Dhttp.address=${OPENSHIFT_DIY_IP} "
#"-Dconfig.resource=${OPENSHIFT_HOMEDIR}/app-root/repo/conf/openshift.conf"
nohup ${APP_COMMAND}


# loads $PLAY_PARAMS
#. ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/load_config

#if [[ ! $? -eq 0 ]]; then
#	exit $?
#fi

#LOG_FILE="${OPENSHIFT_DIY_LOG_DIR}play.log"

#chmod +x ${OPENSHIFT_REPO_DIR}target/start

#APP_COMMAND="${OPENSHIFT_REPO_DIR}target/start $PLAY_PARAMS "\
#"-Dhttp.port=${OPENSHIFT_DIY_PORT} "\
#"-Dhttp.address=${OPENSHIFT_DIY_IP} "\
#"-Dconfig.resource=openshift.conf"

#echo $APP_COMMAND &>> $LOG_FILE
#nohup bash -c "${APP_COMMAND} &>> ${LOG_FILE} 2>&1" &> /dev/null